format:
  html: {toc: true, toc-depth: 4, theme: cosmo}
  revealjs: {theme: solarized, navigation-mode: vertical, transition: slide, background-transition: fade, incremental: true}
project: {type: book}
book:
  chapters: [index.qmd, bjs.evolutionary_computation.index.qmd, bjs.evolutionary_computation.chapter_2_origins.qmd]
  title: Evolutionary Computation Exercises
